# Course configuration — shared by LaTeX, web, and other tools.

author: Kelvin Chan
author-short: K. Chan
institute: University of Western Ontario
logo: ./standalones/WesternU_Horizontal_Full_CMYK

subject: Calculus
subj: Calc
number: 1000A
title: Calculus I

term:
  name: Fall 2026
  start: 2026-09-09
  end: 2026-12-09
  readingweek: 2026-10-12
  noclass:
    - 2026-09-30
    - 2026-10-30
  special:
  assessment:
    - 2026-10-30: Midterm

sections:
  "004":
    calendar: 
      show: true
      colour: false
    days:
      - Tue
      - Thu
    time: 7:00 pm to 8:50 pm
  "005":
    calendar: 
      show: true
      colour: false
    days:
      - Mon
      - Wed
      - Thu
      - Fri
    time: 11:30 am to 12:20 pm
